name: CD
on:
  push:
    branches:
      - main

jobs:
  apply-migrations:
    name: Apply postgres migrations to Supabase
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{secrets.DIRECT_URL}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Update prisma client
        run: npx prisma generate

      - name: Build
        run: npm run build

      - name: Apply migrations to the database
        run: npx prisma migrate deploy --preview-feature

  deploy-backend:
    name: Deploy Fikra backend to Render
    needs: apply-migrations
    runs-on: ubuntu-latest

    env:
      DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

    steps:
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: curl "$DEPLOY_URL"
